// One-time build: converts wc.csv -> data.js (predictions + fixtures config).
// Run: node build.js
const fs = require('fs');

const raw = fs.readFileSync(__dirname + '/wc.csv', 'utf8');

// --- minimal RFC-4180 CSV parser (handles quoted fields + embedded commas/newlines) ---
function parseCSV(text) {
  const rows = [];
  let row = [], field = '', i = 0, inQ = false;
  while (i < text.length) {
    const c = text[i];
    if (inQ) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; continue; }
        inQ = false; i++; continue;
      }
      field += c; i++; continue;
    }
    if (c === '"') { inQ = true; i++; continue; }
    if (c === ',') { row.push(field); field = ''; i++; continue; }
    if (c === '\r') { i++; continue; }
    if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; i++; continue; }
    field += c; i++;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const rows = parseCSV(raw).filter(r => r.length > 4);
const header = rows.shift();

// Column indexes (fixed layout of this form export)
const COL = {
  name: 3,
  matches: [ // [colIndex, fixtureId]
    [4, 'A1'], [5, 'A2'], [7, 'B1'], [8, 'B2'], [10, 'C1'], [11, 'C2'],
    [13, 'D1'], [14, 'D2'], [16, 'E1'], [17, 'E2'], [19, 'F1'], [20, 'F2'],
    [22, 'G1'], [23, 'G2'], [25, 'H1'], [26, 'H2'], [28, 'I1'], [29, 'I2'],
    [31, 'J1'], [32, 'J2'], [34, 'K1'], [35, 'K2'], [37, 'L1'], [38, 'L2'],
  ],
  groupWinner: { A: 6, B: 9, C: 12, D: 15, E: 18, F: 21, G: 24, H: 27, I: 30, J: 33, K: 36, L: 39 },
  doubleGroup: 40,
  r32: 41, r16: 42, qf: 43, sf: 44, final: 45,
  thirdPlace: 46, champion: 47, finalScore: 48,
};

const splitTeams = s => (s || '').split(',').map(x => x.trim()).filter(Boolean);

const players = rows.map(r => {
  const matchPicks = {};
  for (const [idx, fid] of COL.matches) matchPicks[fid] = (r[idx] || '').trim();
  const groupWinnerPicks = {};
  for (const g of Object.keys(COL.groupWinner)) groupWinnerPicks[g] = (r[COL.groupWinner[g]] || '').trim();
  const dg = (r[COL.doubleGroup] || '').replace(/group/i, '').trim().toUpperCase(); // "Group H" -> "H"
  return {
    name: (r[COL.name] || '').trim() || '(no name)',
    matchPicks,
    groupWinnerPicks,
    doubleGroup: dg,
    r32: splitTeams(r[COL.r32]),
    r16: splitTeams(r[COL.r16]),
    qf: splitTeams(r[COL.qf]),
    sf: splitTeams(r[COL.sf]),
    final: splitTeams(r[COL.final]),
    thirdPlace: (r[COL.thirdPlace] || '').trim(),
    champion: (r[COL.champion] || '').trim(),
    finalScore: (r[COL.finalScore] || '').trim(),
  };
});

// Fixtures config: the 24 predicted group matches (home/away as worded in the form).
const FIXTURES = [
  ['A1', 'A', 'Mexico', 'South Africa'], ['A2', 'A', 'Korea Republic', 'Czechia'],
  ['B1', 'B', 'Canada', 'Qatar'], ['B2', 'B', 'Bosnia and Herzegovina', 'Switzerland'],
  ['C1', 'C', 'Brazil', 'Scotland'], ['C2', 'C', 'Morocco', 'Haiti'],
  ['D1', 'D', 'USA', 'Paraguay'], ['D2', 'D', 'Australia', 'Turkiye'],
  ['E1', 'E', 'Germany', "Cote D'Ivoire"], ['E2', 'E', 'Curacao', 'Ecuador'],
  ['F1', 'F', 'Netherlands', 'Tunisia'], ['F2', 'F', 'Japan', 'Sweden'],
  ['G1', 'G', 'Belgium', 'Egypt'], ['G2', 'G', 'IR Iran', 'New Zealand'],
  ['H1', 'H', 'Spain', 'Saudi Arabia'], ['H2', 'H', 'Cabo Verde', 'Uruguay'],
  ['I1', 'I', 'France', 'Norway'], ['I2', 'I', 'Senegal', 'Iraq'],
  ['J1', 'J', 'Argentina', 'Algeria'], ['J2', 'J', 'Austria', 'Jordan'],
  ['K1', 'K', 'Portugal', 'Uzbekistan'], ['K2', 'K', 'Congo DR', 'Colombia'],
  ['L1', 'L', 'England', 'Panama'], ['L2', 'L', 'Croatia', 'Ghana'],
].map(([id, group, home, away]) => ({ id, group, home, away }));

const out =
`// AUTO-GENERATED by build.js from wc.csv. Do not edit by hand.
window.WC_FIXTURES = ${JSON.stringify(FIXTURES, null, 0)};
window.WC_PLAYERS = ${JSON.stringify(players)};
`;
fs.writeFileSync(__dirname + '/data.js', out);
console.log(`Wrote data.js: ${players.length} players, ${FIXTURES.length} fixtures.`);
