// Every tool /find can point to. The flowchart in tree.js refers to tools by url.
//   s: colour family (econ · bm · hist · maths · any)
//   tags: extra search words, never shown
window.TOOLS = [
  { name: "IBecon", url: "/ibecon", s: "econ", desc: "Everything Econ: notes and review for the whole IB Economics course.", tags: "notes syllabus units review" },
  { name: "Samples", url: "/samples", s: "econ", desc: "Model answers revealed step by step, from hint to full paragraph.", tags: "model answer essay scaffold paper 1 paper 2" },
  { name: "Econia", url: "/econia", s: "econ", desc: "The Economics IA, stage by stage, from choosing an article to submitting.", tags: "internal assessment commentary portfolio" },
  { name: "Graph Drawer", url: "/graphs", s: "econ", desc: "Draw economics diagrams and export them as images.", tags: "diagram supply demand curve draw" },
  { name: "EconNews", url: "/econnews", s: "econ", desc: "This week's economics news, picked for IB students.", tags: "news articles current events weekly" },
  { name: "Stock Simulator", url: "/stocksimulator", s: "econ", desc: "Dozens of random price paths, then pick the most convincing-looking one. Patterns in pure noise.", tags: "random walk shares market finance chart" },
  { name: "IBBM", url: "/ibbm", s: "bm", desc: "Everything BM: notes, case studies and exam technique.", tags: "notes syllabus units case studies" },
  { name: "RatIBro", url: "/ratibro", s: "bm", desc: "Learn IB finance: ratios, accounts and practice, with progress saved.", tags: "finance ratios unit 3 accounts" },
  { name: "Slop Study", url: "/slopstudy", s: "bm", desc: "Spin the reels for a random company and theory terms, get a case study and exam questions.", tags: "case study generator slot machine casegen practice" },
  { name: "Busia", url: "/busia", s: "bm", desc: "The BM IA, start to finish, one stage at a time.", tags: "internal assessment research question" },
  { name: "BusiNews", url: "/businews", s: "bm", desc: "Weekly IB BM case studies built from real business news.", tags: "news case study weekly" },
  { name: "Newbiz", url: "/newbiz", s: "bm", desc: "Spin two or three unrelated words, and a constraint, to build a business case out of.", tags: "starter random words spinner entrepreneur" },
  { name: "Review Questions", url: "/qreview", s: "econ", desc: "Random practice from IB past papers. Reveal the answer and mark yourself.", tags: "past papers flashcards practice questions" },
  { name: "Lineup", url: "/lineup", s: "hist", desc: "Card sort for any topic: students line cards up between two extremes, then reveal the notes. Decks made with an AI prompt.", tags: "card sort continuum spectrum deck extent discussion" },
  { name: "AI or us?", url: "/aiorus", s: "hist", desc: "Will AI mirror the Industrial Revolution? A card sort with a live class screen.", tags: "industrial revolution card sort compelling question fmw grade 9" },
  { name: "Griz", url: "/griz", s: "any", desc: "Generate competitive class quizzes from your own content.", tags: "quiz jeopardy trivia teams game starter times tables" },
  { name: "UniQuiz", url: "/uniquiz", s: "any", desc: "Run live quiz sessions. Students join with a PIN and answer on their device.", tags: "quiz kahoot pin devices" },
  { name: "Checkin", url: "/checkin", s: "any", desc: "Question sets for a class you sign in to. Multiple choice marks itself, written answers come back to you.", tags: "concept check test marking quiz exit ticket assessment" },
  { name: "Scrim", url: "/scrim", s: "any", desc: "Pose a question, get student answers projected on your screen from their devices.", tags: "responses board answers project" },
  { name: "Spectra", url: "/spectra", s: "any", desc: "Post statements, students rate on a scale, see the full spectrum of class opinion.", tags: "poll opinion agree disagree vote" },
  { name: "Pulse", url: "/pulse", s: "any", desc: "Students plot themselves on your variables and see the class spread in real time.", tags: "poll scatter response" },
  { name: "Flare", url: "/flare", s: "any", desc: "Real-time help signals from students. See at a glance when your class needs support.", tags: "help lost signal alarm" },
  { name: "Picture Reveal", url: "/reveal", s: "any", desc: "Click squares to reveal the hidden image underneath.", tags: "guess image starter tiles" },
  { name: "Argument Mapper", url: "/argmap", s: "any", desc: "Build structured argument maps: claims, reasons, objections, rebuttals, evidence.", tags: "essay plan argument map debate" },
  { name: "Dowser", url: "/dowser", s: "any", desc: "Freeform canvas of moveable post-its, lines, and arrows for brainstorming.", tags: "sticky notes brainstorm board post-it" },
  { name: "Whiteboard", url: "/wb", s: "any", desc: "A basic, get-out-of-the-way whiteboard.", tags: "draw board" },
  { name: "Cultivar", url: "/cultivar", s: "any", desc: "Vocabulary flashcards with spaced repetition for language learners.", tags: "flashcards vocab language vietnamese spaced repetition" },
  { name: "PeeDeeEffer", url: "/peedeeeffer", s: "any", desc: "Merge, split, and extract text from PDFs privately, entirely on your own device.", tags: "pdf merge split epub" },
  { name: "PDF Annotator", url: "/pdfwrite", s: "any", desc: "Annotate a PDF and download your marked-up copy.", tags: "pdf draw mark up" },
  { name: "Covers", url: "/covers", s: "any", desc: "Find a book's cover and print it big enough for a classroom door.", tags: "book cover print door poster" },
  { name: "Longcut", url: "/longcut", s: "any", desc: "Find a walking or cycling route that favours quiet back streets and paths over main roads.", tags: "map route walk bike quiet" },
  { name: "Pinhole", url: "/pinhole", s: "any", desc: "Design and test pinhole cameras.", tags: "camera photography" },
  { name: "Photos", url: "/photos", s: "any", desc: "A photo gallery.", tags: "pictures gallery" },
  { name: "Is Luxon PM?", url: "/isluxonpm", s: "any", desc: "A live answer to the question on everyone's lips.", tags: "prime minister nz joke" },
  { name: "Evolutionary Race Cars", url: "/racecar", s: "any", desc: "Watch cars evolve over generations to go faster or climb steeper terrain.", tags: "evolution simulation natural selection" },
  { name: "Forest Evolution", url: "/trees", s: "any", desc: "A forest evolves under rainfall, wind, and fire. Height, girth, and seed strategy all compete.", tags: "evolution simulation natural selection trees" },
  { name: "Chaos Visualisation", url: "/chaos", s: "maths", desc: "The hidden patterns that emerge from chaotic systems.", tags: "fractal sierpinski chaos game" },
  { name: "Joined Points", url: "/joinedpoints", s: "maths", desc: "Watch connections form as nearby points are joined.", tags: "network graph points" },
  { name: "Mandelbrot Set", url: "/mandelbrot-v2", s: "maths", desc: "Generate and zoom into the Mandelbrot set.", tags: "fractal complex numbers" },
  { name: "Function Heat Map", url: "/funcheatmap-v2", s: "maths", desc: "Visualise two-variable functions as a colour heat map.", tags: "formula contour graph" },
  { name: "Coordinate Inverter", url: "/cinvert", s: "maths", desc: "Invert points and shapes around a unit circle.", tags: "circle inversion geometry" },
  { name: "Flower Generator", url: "/flowers", s: "maths", desc: "Generate flowers from mathematical patterns.", tags: "phyllotaxis golden ratio spiral" },
  { name: "Algebra Exam Questions", url: "/algeqs", s: "maths", desc: "Solve exam-style algebra with worked solutions.", tags: "ncea algebra equations achieved merit excellence" },
  { name: "Coordinate Geometry", url: "/coordgeo-v1.1", s: "maths", desc: "Practise midpoints and gradients with exam-style questions.", tags: "midpoint gradient graph" },
  { name: "Runners in Sync", url: "/runymxc", s: "maths", desc: "Adjust two runners' speeds so they finish at the same time.", tags: "linear y = mx + c equations" },
  { name: "Discount Dash", url: "/discountdash-v1.0", s: "maths", desc: "Race to find the best deals using percentages.", tags: "percentages money shopping" },
  { name: "Turtle Artist", url: "/turtle", s: "maths", desc: "Young learners stack simple commands to make a turtle draw: a first taste of sequencing, loops, and angles.", tags: "coding programming turtle logo" },
  { name: "Typurr", url: "/typurr", s: "any", desc: "Type words to smash obstacles as Ty the cat. For young typists.", tags: "typing keyboard cat game" },
  { name: "Cat Jump", url: "/catjump", s: "any", desc: "Dodge the cacti in a cat-themed endless runner.", tags: "game runner cat" },
  { name: "Kitty Maze", url: "/kittymaze", s: "any", desc: "Guide Rainbow Cat through the maze.", tags: "game maze cat" },
  { name: "UniChase", url: "/unichase", s: "any", desc: "Steer a unicorn to evade snakes across five difficulty levels.", tags: "game unicorn" },
  { name: "Sudoku", url: "/sudoku", s: "maths", desc: "Four difficulty levels, notes mode, and save strings to resume.", tags: "puzzle logic" },
  { name: "Paper Snowflakes", url: "/snowflake", s: "any", desc: "Fold and cut digital paper to make snowflakes.", tags: "craft paper cut symmetry" },
  { name: "Guess Who Strategy", url: "/guesswhoanimals", s: "any", desc: "Find the optimal questions for the animal version of Guess Who.", tags: "game strategy animals" },
  { name: "AniPics", url: "/anipics", s: "any", desc: "Browse and find animal emojis.", tags: "animals emoji" },
  { name: "Binary Counting", url: "/binary-game-v1.1", s: "maths", desc: "Practise binary number patterns and place values.", tags: "binary place value" },
  { name: "Multiplication Memory", url: "/multiplication-memory-v2.1", s: "maths", desc: "Match multiplication facts in a memory card game.", tags: "times tables memory game" },
  { name: "Fractions", url: "/fractions", s: "maths", desc: "Visualise fractions and their equivalent forms.", tags: "pizza fractions equivalent" },
  { name: "Number Tiles", url: "/numbertiles", s: "maths", desc: "Arrange tiles to practise reading and ordering numbers.", tags: "ordering counting" },
];
